---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian

  tasks:
    - name: Install helpful system utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
        state: present